server:
  port: 7003

eureka:
  instance:
    hostname: aaalanwong-7003.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://aaalanwong-7001.com:7001/eureka, http://aaalanwong-7002.com:7002/eureka
spring:
  application:
    name: eureka-server