server:
  port: 9527

spring:
  application:
    name: micro-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://aaalanwong-7001.com:7001/eureka, http://aaalanwong-7002.com:7002/eureka, http://aaalanwong-7003.com:7003/eureka
  instance:
    instance-id:  gateway-6001.com
    prefer-ip-address: true #访问路径可以显示IP地址


info:
  app.name: micro-zuul-gateway-6001
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  ignored-services: '*'
  prefix: /atguigu
  routes:
    MICRO-PROVIDER: /prov/**
  host:
    max-per-route-connections:
    max-total-connections:




